# -*- coding: utf-8 -*-
"""cli.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YlYmw50AkafKJneFKx1k3-h1rjsyLJ4x
"""

import logic

def display_board(board):
    for row in board:
        print(" | ".join(row))
        print("-" * 9)

def main():
    board = logic.initialize_board()
    current_player = "X"

    while True:
        display_board(board)
        print(f"Player {current_player}, it's your turn!")

        row = int(input("Enter row (0, 1, 2): "))
        col = int(input("Enter column (0, 1, 2): "))

        if logic.is_valid_move(board, row, col):
            logic.make_move(board, row, col, current_player)

            if logic.check_winner(board, current_player):
                display_board(board)
                print(f"Player {current_player} wins!")
                break
            elif logic.is_draw(board):
                display_board(board)
                print("It's a draw!")
                break

            current_player = "O" if current_player == "X" else "X"
        else:
            print("Invalid move, please try again.")

if __name__ == "__main__":
    main()