# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPnQ7t8UA92WOAdTQ2TI3t6YkFwEjSNI
"""

from typing import List

def flood_fill(input_board: List[str], old: str, new: str, x: int, y: int) -> List[str]:
    if x < 0 or x >= len(input_board) or y < 0 or y >= len(input_board[0]) or input_board[x][y] != old:
        return input_board

    input_board[x] = input_board[x][:y] + new + input_board[x][y+1:]

    flood_fill(input_board, old, new, x+1, y)
    flood_fill(input_board, old, new, x-1, y)
    flood_fill(input_board, old, new, x, y+1)
    flood_fill(input_board, old, new, x, y-1)

    return input_board

board = [
    "......................",
    "......##########......",
    "......#........#......",
    "......#........#......",
    "......#........#####..",
    "....###............#..",
    "....#............###..",
    "....##############....",
]

board = [list(row) for row in board]
modified_board = flood_fill(input_board=board, old=".", new="~", x=5, y=12)

for row in modified_board:
    print(''.join(row))